### ISSUE TITLE
[xOBSE22.2-xOBSE22.9]Input functions are not functioning properly with obcn_12416.dll, a Chinese localization plugin

### ISSUE THREAD

**Issue by qq2424711328** [llde/xOBSE#208] opened 2023-07-02 13:35 UTC
The two localized plugins have been uploaded to Mega Drive.      [https://mega.nz/folder/8Wk2HahL#uPKwxt6wGeBKO_bu4k9x2g](url)

**Comment by qq2424711328** [comment] 2023-07-02 13:40
just like this issue [https://github.com/llde/xOBSE/issues/198](url)

**Comment by llde** [comment] 2023-07-02 16:18
what version of OBJA is this? 198 was reported fixed with TES4JaPatch016_beta3

**Comment by qq2424711328** [comment] 2023-07-03 02:50
> what version of OBJA is this? 198 was reported fixed with TES4JaPatch016_beta3
> 
> Is by chance OBCN source code public?

I sincerely apologize for the issue with my report. I admit that there were shortcomings in my research as I did not read the entire xOBSE page, and I became aware of the fix for the Japanese patch in xOBSE 22.8 only after being reminded. Furthermore, despite my best efforts, I have been unable to locate the source code for the Chinese localization plugin. The website where the plugin was originally published has been closed, and I have been unable to contact the developer. I will continue my search for the source code. For now, the only thing I can provide is the Chinese localized plugin that has been uploaded to Mega Drive.

**Comment by llde** [comment] 2023-07-03 07:44
It's possible OBCN is doing a similar hook of what was done with OBJA. If OBCN is frozen (as in not anymore updated) I could try to provide a similar compatibility shim. If OBCN is still developed, differently from OBJA, then  it's better to make a compatibility patch on OBCN side

**Comment by llde** [comment] 2023-08-31 22:51
Hi @qq2424711328  I finally found a bit of time to tackle this issue. 
Unfortunatly OBCN doesn't work for me (it cause the game to crash on start) and this seems a wine regression I would need to debug too (as even OBJA that I know previously was working (I know I tested in directly))
However the good new is that OBCN is strictly linked from OBJA, they share most of the codebase and the compiled result is often very similar (probably they used the same toolchain), with just the offsets (and OBJA strings being replaced with OBCN strings). So I think I can mimick my fix for OBJA, and call it a day, I will however need your assistance to test

**Comment by kuroko137** [comment] 2023-09-18 04:24
Hi @llde, would you like me to help with testing the issues related to OBCN as well? I've been able to get OBCN working (confirmed with the Chinese version of the Unofficial Patch, where characters are displayed correctly. However, I can read Chinese characters but can't understand Chinese at all).
If you're okay with a simple test, please let me know.

**Comment by qq2424711328** [comment] 2023-09-18 04:33
> Hi @qq2424711328 I finally found a bit of time to tackle this issue. Unfortunatly OBCN doesn't work for me (it cause the game to crash on start) and this seems a wine regression I would need to debug too (as even OBJA that I know previously was working (I know I tested in directly)) However the good new is that OBCN is strictly linked from OBJA, they share most of the codebase and the compiled result is often very similar (probably they used the same toolchain), with just the offsets (and OBJA strings being replaced with OBCN strings). So I think I can mimick my fix for OBJA, and call it a day, I will however need your assistance to test

Hi @llde, Thank you so much for your hard work. I am truly eager to collaborate with you, and I'm ready to begin today! Additionally, I want to sincerely apologize for just now noticing your response. I have been quite busy with my studies recently, which is why I didn't see your message earlier.

**Comment by qq2424711328** [comment] 2023-09-18 04:36
> Hi @llde, would you like me to help with testing the issues related to OBCN as well? I've been able to get OBCN working (confirmed with the Chinese version of the Unofficial Patch, where characters are displayed correctly. However, I can read Chinese characters but can't understand Chinese at all). If you're okay with a simple test, please let me know.

Haha, thank you for your kindness and help.

**Comment by llde** [comment] 2023-09-18 08:08
@kuroko137 a simple test should be enough

**Comment by kuroko137** [comment] 2023-09-18 23:39
Sorry, I might have been too nosy.
I tested whether each input function works in 22.10beta + OBCN, and it seems to work perfectly as @qq2424711328 said.
I also tested it again in 22.10beta + OBJA, and it seems to be working fine as well.

**Closed** 2023-09-19 07:41 UTC
Labels: need testing

**Comment by paulbph** [comment] 2023-12-15 14:14
Unfortunately, xOBSE 22.10beta is not working for my Chinese game environment, 
I mean input functionality of OBCN.

Actually it's not working correctly.
OBCN have 3 in-game hotkeys can set,
1. input chinese (simple) UI
2. open vanilla console (I don't know Why Origin Author designed this)
3. OBCN setup UI in game

MY Test reasult
1. not work 
2.  Even I don't  use it , just try,  then i got  CTD
3.  vanilla console is open (0_o !!!?)

MY environment
Windows 10 64bit 22H2 
Oblivion 1.2.0416  (Steam version) 
xOBSE 22.2~xOBSE 22.10beta (not work correctly)
xOBSE 22.1 (work perfectly)
 
Sorry for bother and my poor english.

**Comment by llde** [comment] 2023-12-15 14:28
@paulbph  this was reported fixed for 2 different people, so I believe that this is an issue on your end. 
I would need more information: launch the game with the last beta and provide the obse.log

Also check that the OBCN version is the same version reported here

**Comment by paulbph** [comment] 2023-12-15 14:46
@llde  I'm sure  OBCN version is the same, 
even i change my OBCN provided by qq2424711328, the situation is no different.
https://github.com/llde/xOBSE/issues/208#issuecomment-1617142229

Here is my last obse log, Thanks.

[Uploading obse.log…]()

**Comment by llde** [comment] 2023-12-15 15:04
Umh, I wonder if another plugin is interfering. Can you try with all plugins excpet OBCN off?

**Comment by paulbph** [comment] 2023-12-15 15:17
even enable vanilla plugins + OBSE 22.10 + OBCN only
still not work.

here is obse log 
[obse.log](https://github.com/llde/xOBSE/files/13686760/obse.log)
![1702653123701](https://github.com/llde/xOBSE/assets/7222632/78288d94-c722-4ac0-a0a7-8424c8e1a347)

**Comment by qq2424711328** [comment] 2023-12-15 15:38
> even enable vanilla plugins + OBSE 22.10 + OBCN only still not work.
> 
> here is obse log [obse.log](https://github.com/llde/xOBSE/files/13686760/obse.log) ![1702653123701](https://private-user-images.githubusercontent.com/7222632/290861754-78288d94-c722-4ac0-a0a7-8424c8e1a347.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTQ5NzMsIm5iZiI6MTcwMjY1NDY3MywicGF0aCI6Ii83MjIyNjMyLzI5MDg2MTc1NC03ODI4OGQ5NC1jNzIyLTRhYzAtYTBhNy04NDI0YzhlMWEzNDcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTUzNzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QwZWViYWZlOWQ3ODJmMGY2YTE5MjNmZjQxNWQ2NGIzZWRkNzk5NWVjYjBlZmEzMDhlYWViMGM5NzU2MWE1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SX-hS9glwxEAwBNk23KUGeQoC9boY6Cvjx034zLSOg0)

我重新进入游戏测试了一遍，按键输入确实正常阿

**Comment by paulbph** [comment] 2023-12-15 15:43
@qq2424711328 這就很詭異  另外除了按键输入 我想確認一下 
你能在遊戲中 叫出 OBCN的設定畫面嗎?
就這個
![1702653123701](https://github.com/llde/xOBSE/assets/7222632/a49814dd-1a5b-47f7-9cc4-68f374a934ba)

**Comment by qq2424711328** [comment] 2023-12-15 16:06
> @qq2424711328 這就很詭異 另外除了按键输入 我想確認一下 你能在遊戲中 叫出 OBCN的設定畫面嗎? 我是不行 Orz 就這個 ![1702653123701](https://private-user-images.githubusercontent.com/7222632/290868523-a49814dd-1a5b-47f7-9cc4-68f374a934ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTYwMDMsIm5iZiI6MTcwMjY1NTcwMywicGF0aCI6Ii83MjIyNjMyLzI5MDg2ODUyMy1hNDk4MTRkZC0xYTViLTQ3ZjctOWNjNC02OGYzNzRhOTM0YmEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTU1NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDNjODBkMDA2NTRkYzU3OTZjOGJlZDBhYzg0NzNiNDUzMTdjYzFiMTFmYzlkZjQ1NzYyZjhjMWEwYTg3MGVkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sKTzS4Rm8pkNu9JCB-e4Ewf0RggtA-wZZm5cnnOGzvc)

当我按下F11键想要呼出obcn菜单时，像你描述的那样呼出了游戏内的控制台，当我按下f8键时游戏则发生了闪退。
值得一提的事情是，当我在obse22.10beta+obcn+enb+combat addition（一个战斗模组）的纯净游戏里，按键仍然生效

**Comment by qq2424711328** [comment] 2023-12-15 16:24
> @qq2424711328 這就很詭異 另外除了按键输入 我想確認一下 你能在遊戲中 叫出 OBCN的設定畫面嗎? 我是不行 Orz 就這個 ![1702653123701](https://private-user-images.githubusercontent.com/7222632/290868523-a49814dd-1a5b-47f7-9cc4-68f374a934ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc2OTAsIm5iZiI6MTcwMjY1NzM5MCwicGF0aCI6Ii83MjIyNjMyLzI5MDg2ODUyMy1hNDk4MTRkZC0xYTViLTQ3ZjctOWNjNC02OGYzNzRhOTM0YmEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTYyMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhmMjgwZWVmNDRmMmQxNTAxOWRhOWEzODRiMzIxZTJmMjdkNzA4M2EzYjU1ZTcxY2U3YjMxOGE3OTZkMmZjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kRI-HxJwMKGUDnzaOgk1oGPWlDAgwm5bGxzxkygAJCI)

[Oblivion Log.zip](https://github.com/llde/xOBSE/files/13687407/Oblivion.Log.zip)
这里是我的日志文件 可能会有用

**Comment by paulbph** [comment] 2023-12-15 16:27
好的 感謝 我等下看看
剛剛嘗試  obse22.10beta+obcn+enb 的純淨環境 依舊是不行 Orz
